mozilla/lookml-generator

generator/namespaces.py

Make the view blocklist in namespaces.yaml configurable

---

generator/namespaces.py
tests/test_namespaces.py

Differentiate stable and derived views

---

generator/explores.py
generator/lookml.py
generator/namespaces.py
requirements.in
requirements.txt
tests/test_lookml.py

- Use lkml for lookml generation / comparison
- Add some logging about generation

Generate explores for Ping Tables

---

generator/namespaces.py
generator/views.py

The output right now is exactly the same as before. Next step will be to expand the GrowthAccountingView to create a view, and then an explore.

View classes

---

.circleci/config.yml
Dockerfile

Circleci fails with
Step 14/20 : COPY --chown=${USER_ID}:${GROUP_ID} requirements.txt ${HOME}
unable to convert uid/gid chown string to host mapping: can't find uid for user ${USER_ID}: no such user: ${USER_ID}
Exited with code exit status 1
CircleCI received exit code 1

Lookml generator fix container build

---

README.md
bin/generate
docker-compose.yml

- Pull out common operations to function (for comitting)
- Makes the hub publish branch exactly match the source, rather
than cherry-picking

Update spoke repo in bin/generate

---

.pre-commit-config.yaml

This would have saved me a bit of time earlier today, I think. /cc @fbertsch

Add mypy to list of pre-commit hooks

---

generator/explores/ping_explore.py
tests/test_lookml.py

Whoops. Have verified this is correct.

Fix always_filters syntax

---

generator/explores/__init__.py
generator/explores/glean_ping_explore.py
generator/lookml.py
generator/namespaces.py
generator/views/__init__.py
generator/views/glean_ping_view.py
generator/views/growth_accounting_view.py
generator/views/ping_view.py
generator/views/table_view.py
generator/views/view.py
tests/conftest.py
tests/test_lookml.py
tests/test_namespaces.py

This is horrible and hacky, but would appreciate some feedback if I'm on the right track. It does seem to yield valid results in my initial (very cursory) testing.

Generate glean dictionary links for metric columns in pings (fixes #64)

---

generator/explores/__init__.py
generator/explores/client_counts_explore.py
generator/explores/explore.py
generator/explores/ping_explore.py
generator/lkml_update.py
generator/lookml.py
generator/views/__init__.py
generator/views/client_count_view.py
generator/views/client_counts_view.py
generator/views/growth_accounting_view.py
generator/views/ping_view.py
generator/views/table_view.py
generator/views/view.py
tests/test_lookml.py
tests/test_namespaces.py
tests/test_updated_lkml_parser.py

- Add updated lkml parser to address https://github.com/joshtemple/lkml/issues/53

Add Client Counts view and explore

---

bin/generate
generator/explores/client_counts_explore.py
generator/explores/explore.py
generator/explores/growth_accounting_explore.py
generator/explores/ping_explore.py
generator/lkml_update.py
generator/views/ping_view.py
generator/views/table_view.py
tests/test_lookml.py

Fixes https://github.com/mozilla/lookml-generator/issues/90.

Fix filter suggests to work for views

---

generator/views/glean_ping_view.py
tests/test_lookml.py

Ignore glean metrics missing from BQ

---

namespaces-allowlist.yaml

Tested this on dev, a few things are odd (e.g. test metrics), but we can fix those up later.

Enable bergamot

---

Dockerfile
requirements.in
requirements.txt

~~It appears that something broke with 3.8.10?~~

Tighter version pinning of docker containers, update python requirements

---

.circleci/config.yml
netlify.toml

This PR will have two parts:
1. Factor out generation of namespaces/lookml into a seperate script (and test that works per PR in Circle)
2. Generate namespaces/lookml in netlify and publish to a location that we can consume (probably initially something like lookml-generator.netlify.app)

Bug 1707727 - Test generation of namespaces.yaml and make it available in deploy preview

---

requirements.txt

Bump google-api-core dependency

---

README.md

Correct typo and update markdown in README

Correct typo and update markdown in README

---

custom-namespaces.yaml
generator/explores/explore.py
namespaces-allowlist.yaml

This was tested in the `activity_stream` branches of hub and spoke. Everything there seems to be working; we'll have to add a few measures manually.

Bug 1711955 - Activity stream

---

custom-namespaces.yaml
generator/spoke.py
generator/views/lookml_utils.py
generator/views/ping_view.py
namespaces-allowlist.yaml
tests/test_lookml.py
tests/test_spoke.py

I tested this in the `contextual-services` branch. I can confirm that I can query the table using the bigquery-oauth connection.

Bug 1711955 - Add contextual services namespace

---

netlify.toml

See mozilla/glean-dictionary#639

Abort when any step of the netlify deploy fails

---

custom-namespaces.yaml

I figured we should enable all the contextual services data and hold a demo at some point with the team. @BenWu I was under the impression that you've been working with this, right?

Add remaining contextual-services tables

---

generator/explores/__init__.py
generator/explores/client_counts_explore.py
generator/explores/explore.py
generator/explores/funnel_analysis_explore.py
generator/explores/growth_accounting_explore.py
generator/explores/ping_explore.py
generator/lookml.py
generator/views/__init__.py
generator/views/funnel_analysis_view.py
generator/views/view.py
tests/test_funnel_analysis.py
tests/test_lookml.py
tests/test_namespaces.py
tests/utils.py

Fixes #76 and Fixes #87. New views/explores should be able to follow this pattern of "Create a test file".
Tested on the branch `funnel_analysis`, there will be an explore on that branch for Fenix funnels.

Funnel analysis explores

---

generator/views/glean_ping_view.py
tests/test_lookml.py

- Change key to label
- Change the way the view is displayed

Minor changes to labeled counters

---

bin/generate
custom-namespaces.yaml
generator/namespaces.py
generator/spoke.py
tests/test_namespaces.py
tests/test_spoke.py

Fixes #163.
Tested on looker-spoke-private: https://github.com/mozilla/looker-spoke-private/tree/explicit_spokes-working

Add ability to specify looker-spoke-private

---

GENERATION_DISALLOW_LIST
bin/generate

Tested here: https://github.com/mozilla/looker-hub/tree/add_ios_explores/firefox_ios/explores
More removal!

Allow for generating iOS Explores

---

generator/explores/__init__.py
generator/explores/events_explore.py
generator/explores/explore.py
generator/views/__init__.py
generator/views/events_view.py
generator/views/glean_ping_view.py
generator/views/ping_view.py
generator/views/view.py
tests/test_events.py
tests/utils.py

This currently won't create any new views for any datasets, since we haven't switched to the app-datasets for Glean apps.

Add event counts view

---

requirements.in
requirements.txt

Update google-api-core to 1.31.0

---

custom-namespaces.yaml

This should eventually be fixed by https://github.com/mozilla/lookml-generator/issues/133

Fix incorrect key name

---

bin/generate

Fix command for checking out publish branch

---

generator/spoke.py

I tested it locally and the exception did not get raised.

Check if Looker SDK is set up before initialization

---

README.md

Add docs for adding custom namespaces to README (fixes #70)

---

namespaces-allowlist.yaml

[issue](https://mozilla-hub.atlassian.net/browse/LOOK-107)

LOOK-107 - Add focus android namespace folders

---

generator/explores/glean_ping_explore.py
generator/explores/ping_explore.py
tests/test_lookml.py

Reverts mozilla/lookml-generator#207

Revert "Add examples to Ping explore and Glean ping explore (fixes #107)"

---

namespaces-disallowlist.yaml

New app that has been added but lookml-generator should ignore

Disallow mlhackweek_search

---

custom-namespaces.yaml

https://mozilla-hub.atlassian.net/browse/LOOK-109
Adds the New Tab namespace

[Look-81] Add New Tab namespace

---

custom-namespaces.yaml

Namespace for everything experimentation related

Add experimentation namespace

---

custom-namespaces.yaml

Reverts mozilla/lookml-generator#248

Revert "Remove views referencing experiment project"

---

.circleci/config.yml
custom-namespaces.yaml
generator/explores/__init__.py
generator/explores/explore.py
generator/explores/operational_monitoring_explore.py
generator/namespaces.py
generator/views/__init__.py
generator/views/operational_monitoring_histogram_view.py
generator/views/operational_monitoring_scalar_view.py
generator/views/operational_monitoring_view.py
netlify.toml
requirements.in
requirements.txt
tests/test_namespaces.py
tests/test_operational_monitoring.py

This really doesn't do what it needs to yet. I'm just putting up a WIP thats more of a template

Operational Monitoring Views + Explores

---

README.md

* Newer instructions on authenticating to gcloud
* Add instructions on generating lookml/namespaces without doing a full
deployment

A couple of README updates

---

custom-namespaces.yaml

https://mozilla-hub.atlassian.net/browse/DENG-52

Add accessibility namespace

---

generator/lookml.py

For https://github.com/mozilla/lookml-generator/issues/315
This is what it would look like: https://github.com/mozilla/looker-hub/blob/da727c036fa1802d5a496c9d2d5ca57f18c46f01/awesome_bar/views/urlbar_clients_daily.view.lkml#L2

Add comment to generated contents that files are generated

---

generator/dashboards/operational_monitoring_dashboard.py
generator/dashboards/templates/dashboard.lkml
generator/namespaces.py
tests/test_namespaces.py
tests/test_operational_monitoring.py

Some UI tweaks for the generated opmon dashboards

Adjust series colours and y-axis scale for opmon.

---

custom-namespaces.yaml

Supporting https://mozilla-hub.atlassian.net/browse/DENG-50

Added CASA namespace

---

custom-namespaces.yaml

Add regrets reporter summary view

---

custom-namespaces.yaml
generator/views/events_view.py
tests/test_events.py

Adds a new explore based on `fxa_content_auth_events`
Generated results are on https://github.com/mozilla/looker-hub/tree/ascholtz-fxa-auth-1
cc @kirill-demtchouk

Fxa auth events

---

Dockerfile
README.md
requirements.in
requirements.txt

to work around https://github.com/pypa/pip/issues/9644
see also https://github.com/mozilla/gcp-ingestion/pull/2001

Use --no-deps when installing compiled requirements files

---

custom-namespaces.yaml

[DS-1729](https://mozilla-hub.atlassian.net/browse/DS-1729)

DS-1729 - expose fxa stdout events in Looker

---

custom-namespaces.yaml

DS-1729 - Add explore for fxa stdout events

---

custom-namespaces.yaml

Added a shared namespace with the countries view, to make it available to the private spoke

Added shared namespace

---

bin/generate

Some left-over `content` calls that need to be removed. I'll go ahead with merging to unblock the lookml generator run

Remove generate_looker_content call

---

.Dockerignore
.dockerignore
.gitignore
Dockerfile

List of changes:
- Added `.vscode` to `.gitignore`
- `.dockerignore` added to exclude some files from the image which I believe should not be needed
- Updated deprecated `MAINTAINER` tag to `LABEL`
- Making sure `no-cache` flags are passed when installing packages
- Condensed Docker commands into fewer commands
- Commented out (for now) 3 OS packages, image builds fine. Could those be needed for anything else?

feat: Dockerfile tweaks

---

.circleci/config.yml

blocks #436
copied from bigquery-etl:
https://github.com/mozilla/bigquery-etl/blob/a72ecf7f598cf71b48c47bb7117440e8893a5456/.circleci/config.yml#L88

Ignore comments when verifying requirements.txt

---

custom-namespaces.yaml

Initial PR for adding the new aggregation table to Looker.

fix indentation

---

custom-namespaces.yaml

added marketing namespace with 2 acoustic table views
Part of https://mozilla-hub.atlassian.net/browse/DENG-17

added marketing namespace with 2 acoustic table views

---

custom-namespaces.yaml

Depends on https://github.com/mozilla/bigquery-etl/pull/2965/

Add cohort daily statistics to combined browser metrics namespace

---

generator/dashboards/operational_monitoring_dashboard.py

Fix incorrect tuple type in opmon dashboard

---

generator/explores/client_counts_explore.py
generator/explores/explore.py
tests/test_lookml.py

and reference time_partitioning_field instead of a static submission_date

Only reference app_build in client counts explore if available

---

custom-namespaces.yaml

renamed a view to make it explicit that it is change events and added view for as of today state (build on top of a dedup table for acoustic contacts)

Added acoustic_contacts_current_snapshot view (+ rename)

---

custom-namespaces.yaml
generator/namespaces.py
namespaces-disallowlist.yaml
tests/test_namespaces.py

This refactoring addresses this issue: https://github.com/mozilla/lookml-generator/issues/326

add wildcard to rally- and pioneer-

---

bin/generate

Temporary fix for: https://bugzilla.mozilla.org/show_bug.cgi?id=1774030

[Bug 1774030] Temporarily disable auto reviewer asignment on PRs

---

generator/views/lookml_utils.py

Fixes https://github.com/mozilla/lookml-generator/issues/471

[Bug 1776762] Handle duplicate start and end date dimensions

---

custom-namespaces.yaml

What the title says! 
🍐 with @Marlene-M-Hirose on this

Add sanitization job languages table to search-private group

---

custom-namespaces.yaml

For testing defining dimensions and measures

Added link to temporary newtab_interactions table for View/Explore 

---

custom-namespaces.yaml

Follow-up to #477 and https://github.com/mozilla/bigquery-etl/pull/3073

Use production newtab_interactions table

---

custom-namespaces.yaml

We updated the table schema!
Now this view needs to pull from this table.

Switch medatada daily view to the new updated table in BQ

---

custom-namespaces.yaml

Similar to https://github.com/mozilla/lookml-generator/pull/385  -- RE https://mozilla-hub.atlassian.net/browse/DO-827

DO-827 Create firefox iOS topsites impression event ping view and explore

---

generator/views/funnel_analysis_view.py
tests/test_funnel_analysis.py

chore(DVPN-178): regex generation SQL string formatting tweaks

---

generator/views/funnel_analysis_view.py
tests/test_funnel_analysis.py

chore(DVPN-178): reformatted SQL for event_types

---

generator/views/funnel_analysis_view.py
tests/test_funnel_analysis.py

bug(DVPN-178): VPN event funnel not showing - quick fix 

---

custom-namespaces.yaml

Add firefox_products_search_clients_engines_sources_daily to the custom namespace to make it available in Looker.

Add firefox_products_search_clients_engines_sources_daily view

---

custom-namespaces.yaml

Add Firefox for Families forecast data

---

.gitignore
README.md

chore: added Generate Command Explained to README

---

custom-namespaces.yaml

depends on: https://github.com/mozilla/bigquery-etl/pull/3214

added fxa-users-services to custom-namespaces.ysml

---

custom-namespaces.yaml

See https://mozilla.slack.com/archives/C4D5ZA91B/p1663787608190659

Add default browser agent explore

---

generator/dashboards/operational_monitoring_dashboard.py
generator/dashboards/templates/dashboard.lkml
generator/views/operational_monitoring_alerting_view.py
generator/views/operational_monitoring_view.py
tests/test_operational_monitoring.py

Add date filter to opmon dashboards

---

custom-namespaces.yaml

Add a new section called `revenue private` for revenue review (budget, forecast etc)

Update custom-namespaces with a new section

---

generator/operational_monitoring_utils.py

Speed up lookml-generator namespaces

---

generator/views/glean_ping_view.py
tests/test_glean_ping_view.py
tests/test_lookml.py

Ignore glean probes not present in table schema

---

custom-namespaces.yaml

feat: added dim to custom namespaces, should go inside lookmlgenerator

---

custom-namespaces.yaml

Added usage and table views to monitoring namesapce

Added usage and table views to monitoring namesapce

---

custom-namespaces.yaml

Depends on: https://github.com/mozilla/bigquery-etl/pull/3204

feat(): added monitoring_airflow namespace

---

custom-namespaces.yaml

To unblock lookml-generator from failing

Fix Airflow tables

---

custom-namespaces.yaml

More context: https://mozilla-hub.atlassian.net/browse/LOOK-129

Add Glean Events explore for Firefox Desktop

---

.pre-commit-config.yaml
custom-namespaces.yaml

1. Added site events table (moz-fx-data-marketing-prod.ga_derived.www_site_events_metrics_v1) custom custom-namespaces.yaml 
2. Edited  .pre-commit-config.yaml by changing  isort from 5.10.1 to 5.12.0.

added site events table to the lookml generator 

---

custom-namespaces.yaml

I want to add my new view to looker, so please let me know if that is how to do it :)

add fivetran costs to looker

---

custom-namespaces.yaml

Add daily_active_rows to fivetran 

---

custom-namespaces.yaml

[DENG-683](https://mozilla-hub.atlassian.net/browse/DENG-683):
Added new view for bigquery usage costs. This is needed for creating a looker dashboard for costs.

Added bigquery usage cost view

---

generator/views/datagroups.py
tests/test_datagroups.py

Addresses #622 by writing each datagroup to a separate datagroups.lkml file. 
Before:
```
namespace/
└ datagroups.lkml
```
After:
```
namespace/
└ datagroups/				
└ datagroup_1.lkml
└ datagroup_2.lkml
```
There's currently only one of these in use (https://github.com/mozilla/looker-spoke-default/pull/505) I'll update this after merging and re-running the generator.

Modified datagroup generation to write to datagroups directory

---

custom-namespaces.yaml

switching out the underlying table for fivetran namespace

fivetran costs - change table

---

custom-namespaces.yaml

[DENG-681](https://mozilla-hub.atlassian.net/browse/DENG-681): Intake Hubs Subscriptions Data for Visualization

Add Hubs namespace (DENG-681)

---

namespaces-disallowlist.yaml

Per a discussion in slack with @Dexterp37, these are in-use and would be beneficial to have in Looker.

Remove some apps from disallowlist

---

custom-namespaces.yaml

feat: updated datasets for dim / data_monitoring datasets and adding explores

---

custom-namespaces.yaml

Follow up to https://github.com/mozilla/bigquery-etl/pull/3762

Add newtab visits table view

---

generator/views/client_counts_view.py

Also add a space after periods, for prettier viewing in Looker.

Cast INTERVAL to int for cohort analyses

---

custom-namespaces.yaml

feat(DENG-1017): added an events view and events explore for fxa_all_events

---

custom-namespaces.yaml

requires https://github.com/mozilla/bigquery-etl/pull/4065

DS2642 - Add custom view of stripe tax report

---

custom-namespaces.yaml

Adding consolidated_ad_metrics under new Ads superset

[AD-78] Update custom-namespaces.yaml

---

generator/spoke.py
tests/test_spoke.py

Looker API 3.1 has been disabled by Looker.

Use Looker API 4.0

---

custom-namespaces.yaml

Added adjust table created by Marlene

adding new adjust table

---

custom-namespaces.yaml

feat(): Adding firefox_ios funnel_retention_week_4 table view to custom-namespaces.yaml

---

custom-namespaces.yaml

Adds the `reference` dataset and `macroeconomic_indices` view to custom-namespaces

Add reference dataset to namespaces

---

custom-namespaces.yaml

adding review checker namespace to custom-namespaces.yaml with new derived tables.

add review checker namespace

---

custom-namespaces.yaml

Related  to https://mozilla-hub.atlassian.net/browse/DENG-1781
The temporary view added as part of this PR needs to be removed after validation.

DENG-1781 - Add the v2 table and temp view for urlbar events

---

custom-namespaces.yaml

Remove urlbar temp view created as part of PR 792

DENG-1781 - Remove urlbar temp view

---

custom-namespaces.yaml

Adding moz-fx-data-marketing-prod.google_play_store.Store_Performance_country_v1 to looker

android store performance upload

---

custom-namespaces.yaml

To get the fxa login funnels into Looker. We'll have to wait until the table got deployed (ca. 20 min)

Add Fxa Login funnels

---

generator/dashboards/operational_monitoring_dashboard.py
generator/dashboards/templates/dashboard.lkml
tests/test_operational_monitoring.py

this might complain in the tests ... at least it does locally ... either flake8 is unhappy or the comparison breaks for test_dashboard_lookml_group_by_dimension ... but it's past 9pm on a friday and I'm out of ideas so ...

remove summed cards for group by

---

custom-namespaces.yaml

feat(): added table explores for fenix and firefox_ios feature usage table views

---

custom-namespaces.yaml

[ticket](https://mozilla-hub.atlassian.net/browse/DENG-2223)
adding new tables to looker
don't merge before those views are created by DENG-2219, DENG-2220 and DENG-2221

DENG-2223 add telemetry dev cycle data to looker

---

custom-namespaces.yaml

Deng 2223 telemetry dev cycle dashboard

---

custom-namespaces.yaml

Create new named view and explore for accounts aggregates BQ table
https://mozilla-hub.atlassian.net/browse/DENG-2228

Add accounts aggregates namespace

---

custom-namespaces.yaml

Follow up to https://github.com/mozilla/lookml-generator/pull/840

Fix accounts_aggregates explore

---

custom-namespaces.yaml

Create view and Explore for oauth client ID to name mapping

Add oauth client ID table and explore

---

custom-namespaces.yaml

don't merge before the view is landend in mozdata!

DENG-2223 add data_review_stats to looker

---

generator/views/lookml_utils.py

Follow up to https://github.com/mozilla/lookml-generator/pull/854

Fix handling event stream tables

---

custom-namespaces.yaml

Adding new GA4 derived table:
- ga4_firefox_whatsnew_summary

DENG-2492 add new ga4_firefox_whatsnew_summary table

---

custom-namespaces.yaml

- Added the new GA4 blogs_sessions_v2 table to custom namespaces YAML

DENG-2492 add new GA4 table blogs_sessions_v2

---

custom-namespaces.yaml

feat(): added firefox_ios clients_activation

---

custom-namespaces.yaml

feat(DENG-2913): add firefox_ios_clients view and explore to firefox_ios namespace
One this PR is merged, we need to re-run lookml-generator task.

feat(DENG-2913): add firefox_ios_clients view and explore to firefox_ios namespace

---

custom-namespaces.yaml

feat(DENG-2912): add firefox_android_clients view and explore to the fenix namespace

---

.circleci/config.yml

feat(): Bump gpc-gcr orb version to address pipeline errors.

---

.circleci/config.yml

bug(): Fix errors related to Docker

---

custom-namespaces.yaml

Add monitor_mozilla_accounts_funnels

---

custom-namespaces.yaml

depends on: https://github.com/mozilla/bigquery-etl/pull/5122

DO NOT MERGE: feat(): Updated Acoustic references to use mozdata views for accessing the data

---

custom-namespaces.yaml

View and Explore lines for Email First funnels for Mozilla Accounts.

Add Email First view/explores to custom-namespace

---

custom-namespaces.yaml

Update source of Growth Account explore for Firefox Accounts to use Glean data source, with added service dimension for retention by service.

Update source for Growth Accounting explore

---

custom-namespaces.yaml

This PR is to add 3 new tables with data from Cloudflare:
- browser_usage: mozdata.analysis.cloudflare_browser_usage_data
- device_usage: mozdata.analysis.cloudflare_device_usage_data
- operating_system_usage: mozdata.analysis.cloudflare_os_usage_data

DENG-3260 - add 3 new cloudflare tables

---

custom-namespaces.yaml

Including service dimension for existing funnels. Will likely remove existing explores without the service dimension once I verify it works as expected.

Update custom-namespaces.yaml to include service funnel dimension

---

custom-namespaces.yaml
namespaces-disallowlist.yaml

This is all stuff that hasn't been queried in the last 180 days
Depends on https://github.com/mozilla/looker-spoke-default/pull/797/files

Remove unused content

---

custom-namespaces.yaml

The tables have column descriptions

Point to table rather than view

---

generator/views/events_view.py
tests/test_events.py

Re-declaring the `sql` is incorrect.

Remove  from event_id dimension in final view

---

custom-namespaces.yaml

Create namespace for Firefox engagement and retention data models

Create Firefox OKRs namespace

---

custom-namespaces.yaml

Follow up from https://github.com/mozilla/bigquery-etl/pull/5554
Adding the mobile retention view to Looker

Add view for mobile retention OKR

---

custom-namespaces.yaml

Add Desktop Retention view from https://github.com/mozilla/bigquery-etl/pull/5575

Add Desktop Retention to Firefox OKRs

---

custom-namespaces.yaml

Follow up from https://github.com/mozilla/bigquery-etl/pull/5525

Add mobile engagement to Firefox OKRs

---

generator/views/metric_definitions_view.py

Fixes https://mozilla.slack.com/archives/C01J4BPCYGM/p1716394737699449

Fix date filters for metrics definitions views

---

generator/views/metric_definitions_view.py
requirements.in
requirements.txt

Adding a new statistic for metrics in Looker to compute rolling averages.
Depends on https://github.com/mozilla/metric-hub/pull/430

Add running_average statistic for metrics

---

custom-namespaces.yaml

Add Explore for registration funnel using legacy events.

Update custom-namespaces.yaml to include registation funnel using legacy events

---

generator/lookml.py

For testing some changes locally it would be convenient if it's possible to select specific namespaces that should be generated

Add --only parameter to generate lookml only for select namespaces

---

generator/lookml.py

This makes some changes to the lookml generation to generate views, explores and dashboards in parallel. Not all of the generation can run in parallel since, for example, the explore generation depends on generated view files.
In the tests that I ran locally, this speeds up lookml generation by 2x

Parallel lookml generation

---

generator/lookml.py

Reverts mozilla/lookml-generator#994

Revert "Parallel lookml generation"

---

custom-namespaces.yaml

Update project for site_metrics_summary_v2

---

custom-namespaces.yaml

Reverts mozilla/lookml-generator#1047

Revert "Update custom-namespaces.yaml"

---

custom-namespaces.yaml

feat: telemetry.mobile_new_profiles added to firefox_okrs namespace

---

.circleci/config.yml
.circleci/post-diff.js

This is running the LookML generation in CI and will post a change diff as a comment to the PR. For generating the change diff the generated LookML is compared to the `main` [looker-hub](https://github.com/mozilla/looker-hub) branch.

Show change diff in CI

---

namespaces-disallowlist.yaml

People are interested in looking at them

Re-enable firefox_desktop_background_defaultagent

---

custom-namespaces.yaml

https://mozilla-hub.atlassian.net/browse/DENG-6196

[DENG-6196] Add views for shredder and expiration monitoring

---

custom-namespaces.yaml

The initial health table is working so expanding to add the additional health tables

Add additional accounts health tables

---

custom-namespaces.yaml

fix lookml error due to auto-generated count column

---

custom-namespaces.yaml

feat: add app_store_choice_screen_engagement to the firefox_ios namespace

---

custom-namespaces.yaml

https://mozilla-hub.atlassian.net/browse/DENG-6141
This is to make the Jira Service Desk tables available in Looker

Surface Jira Service Desk tables

---

custom-namespaces.yaml

feat: add bigeye_usage to the monitoring namespace

---

custom-namespaces.yaml

depends on https://github.com/mozilla/bigquery-etl/pull/6656

Add jira multiselect history view and explore

---

custom-namespaces.yaml

This adds `moz-fx-data-shared-prod.jira_service_desk.user` to Looker

Add jira service desk user table

---

custom-namespaces.yaml

Looks like these datasets got deleted

Remove deleted revenue_cat3_analysis datasets

---

custom-namespaces.yaml

feat: Replace task_duration_sum measure with task_duration_seconds

---

custom-namespaces.yaml

Adds a view and explore for `moz-fx-data-shared-prod.telemetry.experiment_crash_rates_live`

Add experiment_crash_rates

---

custom-namespaces.yaml

https://mozilla-hub.atlassian.net/browse/DENG-6141

Add Jira service desk field option view and explore

---

custom-namespaces.yaml

Hi. It's me.  These are front-end performance lighthouse scores, generated daily.  I'd like to put up a dashboard for them in looker.  Thanks

Add fxa health lighthouse scores

---

custom-namespaces.yaml

This adds a looker_dashboard_load_times explore to analyse Looker dashboard load times

Add looker_dashboard_load_times explore

---

custom-namespaces.yaml

See https://github.com/mozilla/telemetry-airflow/pull/2171

Update fxci references

---

custom-namespaces.yaml

Decided to just put 1 version of cohort weekly statistics with all possible aggregates instead of the other 2 simpler ones that can be calculated from this version

DENG-7970 - cohort weekly statistics

---

custom-namespaces.yaml

Adds a namespace for the `device_manufacturer_partnerships` dataset.

Add device manufacturer partnerships namespace

---

custom-namespaces.yaml

Adds Looker views for the BigQuery views added in https://github.com/mozilla/bigquery-etl/pull/7208.

Add SubPlat service subscriptions views (DS-3083)

---

custom-namespaces.yaml

@sean-rose r? if you have a moment

[fxa] add twilio

---

custom-namespaces.yaml

feat: deprecate acoustic

---

generator/views/metric_definitions_view.py

https://mozilla-hub.atlassian.net/browse/DENG-8386
Previously, time or date dimensions were not added to generated metric definition views due to naming collisions when stripping suffixes from time dimension names. This will add time dimensions and ensure that there are not duplicate time dimensions being generated.

[DENG-8386] Generate time dimensions for metric definition views

---

custom-namespaces.yaml

Adds `mozdata.fenix.new_profile_activation_clients` to the growth namespace

Add mozdata.fenix.new_profile_activation_clients to namespaces YAML

---

custom-namespaces.yaml

https://mozilla-hub.atlassian.net/browse/DENG-8625
Add explores and views to create a dashboard for Looker usage monitoring. Based on data collected with henry

[DENG-8625] Add Looker usage monitoring views and explores

---

custom-namespaces.yaml

Reverts mozilla/lookml-generator#1232

Revert "[DENG-8625] Add Looker usage monitoring views and explores"

---

custom-namespaces.yaml

This PR removed the Looker view: 
* serp_categorization_unnested

feat(DENG-9334): Remove unused Looker view, serp_categorization_unnested

---

.flake8
generator/explores/metric_definitions_explore.py
generator/views/metric_definitions_view.py

Fixes https://github.com/mozilla/lookml-generator/commit/4b136cb5937020540a4e258e485531dddc0493d4
The issue was the check on the `analysis_period` filter, which should have been 
`{% if analysis_period._is_filtered %}`

Period over period support fix

---

custom-namespaces.yaml

Partially fulfills this ticket: https://mozilla-hub.atlassian.net/browse/DENG-9595

Add entries for prototype feature segmentation explore (affects no existing explores) 
