mozilla/lookml-generator

generator/explores.py
generator/namespaces.py
tests/test_namespaces.py

This does nothing yet except expose a new section of `namespaces.yaml` called `explores`. Eventually we'll do a few things:
1. Just use this section to generate LookML, and not need to decipher which explores we need from the views
2. Generate LookML within the explore classes (extensibly, using the dimensions)

Namespaces explores

---

generator/explores.py
generator/lookml.py
generator/namespaces.py
generator/views.py
tests/test_lookml.py
tests/test_namespaces.py

Also created a few more functions and cleaned up `namespaces.py`, and added some more tests for those functions.
This also removes the `_daily` tables, as right now we only create explores for ping tables and _last_seen tables (as the growth_accounting explore).
(No implementation yet of that explore, this just updates the namespaces.yaml)

Return instances of Views rather than dicts

---

generator/__init__.py
generator/spoke.py
tests/test_spoke.py

This assumes the spoke repo is available, and generates directories and a model for namespaces that don't have one yet. Will add to deploy via scripts in https://github.com/mozilla/lookml-generator/pull/32 once that merges.

CLI for update spoke with new namespaces

---

Dockerfile
bin/generate
generator/content.py
generator/spoke.py
generator/views.py
tests/test_spoke.py

We've discovered on stage that the models are not configured after deploy.
We add that here to ease development lifecycle. I've tested on dev and this looks to be successful.
Webhooks ensure that the instance is up-to-date on production.

Configure model after creation

---

generator/content.py
generator/namespaces.py
generator/spoke.py
tests/test_content.py
tests/test_lookml.py
tests/test_namespaces.py
tests/test_spoke.py

- Use pretty_name instead of canonical_app_name
- Add `glean_app` to indicate a namespace is glean

Updates to `namespaces.yaml`

---

generator/spoke.py
tests/test_spoke.py

This mainly effects dev, but could effect prod. Basically what happens is the looker sdk fails if the model config already exists. Now we do only try to config a model if the directory for that namespaces is missing, but the problem was that we haven't been merging in the changes immediately while developing, but the model config is done while the script runs. This ends us up in an inconsistent state where the model is configured but there is no associated lookml file.
We work around that here by first checking if the model config exists.

Don't configure model if already exists

---

custom-namespaces.yaml
namespace_allowlist.yaml

I'm not entirely sure what the process looks like here. Once this gets merged, will the namespace be automatically generated and views will be added to looker-hub? Or do I have to open a PR against looker-hub to add what was generated?
The generated output: https://github.com/scholtzan/looker-hub/tree/ascholtz-numbers-that-matter-generation-test-1

Add numbers_that_matter namespace

---

generator/explores/explore.py
generator/explores/growth_accounting_explore.py
generator/explores/ping_explore.py
generator/lookml.py
tests/test_lookml.py

Only requires a channel when it is present in the view. Fixes #59, Fixes #60.

Require date and channel filters in ping explores

---

GENERATION_DISALLOW_LIST
bin/generate
generator/views/__init__.py
generator/views/table_view.py
namespace_allowlist.yaml
tests/test_namespaces.py

A TableView simply exposes a raw table, with no measures.
Eventually we will import this instead of re-generating
all dimensions multiple times.
@wlach I think this may conflict with your changes. Take a look and let me know, I'd rather not block you, and can rebase on yours once we merge that.

Expose Firefox iOS and add `TableView`

---

generator/explores/ping_explore.py
generator/views/lookml_utils.py
tests/test_lookml.py
tests/test_lookml_utils.py

This hasn't caught us yet, but e.g. `_` is a special char, so when we expose channels they will fail (burnham has no channels so we didn't see anything.)

Allow for special chars in filter expressions

---

.flake8
.gitignore
generator/lookml.py
generator/views/glean_ping_view.py
generator/views/growth_accounting_view.py
generator/views/ping_view.py
generator/views/table_view.py
generator/views/view.py
tests/test_lookml.py
tests/test_namespaces.py

This adds some measures for counters in the glean pings. It looks like there will probably more general ways of handling glean pings, but this is a start.
Here's an example push: https://github.com/mozilla/looker-hub/commit/68cd4f805e068d64f1a841b7a280eb58864fb54a

Add sums and client counts for `metrics.counter`

---

bin/generate
generator/lookml.py
generator/namespaces.py
generator/views/glean_ping_view.py
generator/views/growth_accounting_view.py
generator/views/ping_view.py
generator/views/table_view.py
generator/views/view.py
namespace_allowlist.yaml
requirements.in
requirements.txt
tests/conftest.py
tests/test_lookml.py

Lots of changes here. Let's walk through this during our 1:1.
- Ignore `metrics__` unless they are a known and scraped Glean metric
- Add descriptions from probe-info-service for dimensions
- Only allow certain types as dimensions (e.g. no labeled, no string_list, etc.)
- Expose just the sum of a distribution (see e.g. `sum > 5000` client count or ping count)
- Expose numerator and denominator for rate
- Fix client counts for counters

Glean layout

---

generator/views/growth_accounting_view.py

This is something that could be caught if we integrated with [spectacles](https://www.spectacles.dev/).

Fix spurious comma in growth accounting measure

---

generator/views/lookml_utils.py
tests/test_lookml.py

Fixes #82. Instead shows a label that says e.g. `Client Info: Parsed Start Date`.

Don't nest dimension groups

---

generator/spoke.py
tests/test_spoke.py

Previously, we were not updating the model sets correctly -
because of that, we wouldn't see models configured properly
in prod. This should add the actual model name to the set of
models that are part of each model set.

Use correct naming for model sets

---

requirements.in
requirements.txt

workaround for pypa/pip#9644
similar to https://github.com/mozilla/bigquery-etl/pull/2064

Add transitive google deps for dependabot updates

---

generator/explores/client_counts_explore.py
generator/explores/explore.py
generator/explores/funnel_analysis_explore.py
generator/explores/glean_ping_explore.py
generator/explores/growth_accounting_explore.py
generator/explores/ping_explore.py
generator/lookml.py
tests/test_funnel_analysis.py
tests/test_lookml.py

Format should be `Explore for <x> ping. <x ping description>`. For
example, for the metrics ping, you would see:
```
Explore for the metrics ping. The metrics ping is intended for all of
the metrics that are explicitly set by the application or are included
in the application's metrics.yaml file (except events). The reported
data is tied to the ping's measurement window, which is the time
between the collection of two metrics ping. Ideally, this window is
expected to be about 24 hours, given that the collection is scheduled
daily at 4AM. Data in the ping_info section of the ping can be used to
infer the length of this window.
```

Generate descriptions for Glean Ping explores (fixes #106)

---

generator/views/glean_ping_view.py
tests/test_glean_ping_view.py

We need to be carefully about pings like `addresses-sync`, where the
explore name is snake case, but the original ping name is kebab.

Handle Glean pings with kebab case names (fixes #160)

---

generator/views/lookml_utils.py
tests/test_lookml.py

Fixes https://github.com/mozilla/lookml-generator/issues/138
Adds descriptions to dimensions if they are available in BQ

Pull in descriptions from BQ for dimensions (fixes #138)

---

bin/generate

I believe `mozilla_vpn` is missing views because `lookml-generator` is throwing an error and this script isn't stopping.

Stop generate script if any command exits non-zero

---

generator/views/glean_ping_view.py
tests/test_lookml.py

This additional information isn't necessary, and looks redundant. For example:

Remove type from Glean Metric Dimensions (fixes #99)

---

custom-namespaces.yaml

Removed due to Airflow not having permission to access them. Will just add them manually to spoke

Remove views referencing experiment project

---

generator/views/funnel_analysis_view.py
tests/test_funnel_analysis.py

This PR allows you to specify a single property name and value for
events in the funnel analysis explore. This covers most of the current
set of events for Firefox for Android.
https://mozilla-hub.atlassian.net/browse/DS-1776

Allow specifying an event property to narrow down event funnels (fixes #271)

---

custom-namespaces.yaml
generator/constants.py
generator/dashboards/operational_monitoring_dashboard.py
generator/explores/client_counts_explore.py
generator/explores/events_explore.py
generator/explores/explore.py
generator/explores/funnel_analysis_explore.py
generator/explores/glean_ping_explore.py
generator/explores/growth_accounting_explore.py
generator/explores/operational_monitoring_explore.py
generator/explores/ping_explore.py
generator/lookml.py
generator/operational_monitoring_utils.py
generator/views/lookml_utils.py
tests/test_events.py
tests/test_funnel_analysis.py
tests/test_operational_monitoring.py

This PR adds aggregate tables to Operational Monitoring explores to speed up their loading. [This branch](https://github.com/mozilla/looker-hub/tree/emtwo/aggregate_tables) in looker-hub has the changes that can be tested.
In order to add an aggregate table for each metric, the set of metrics associated with an explore need to be available to it including that metric's default values so it can be placed in the aggregate table. This data was already being processed in the dashboard. 
In order to avoid doing the same processing twice - in explores and in dashboards, I factored out that processing in the dashboard and turned it into generic data functions that can be applied to any namespace, called only once to perform processing, and accessed in both explores and dashboards.

Add aggregate tables to speed up operational monitoring dashboards.

---

generator/views/lookml_utils.py

the opmon files depending on this were being regenerated every day unnecessarily because the ordering changed.

Sort opmon dimensions so files are not regenerated unecessarily.

---

generator/dashboards/operational_monitoring_dashboard.py
generator/dashboards/templates/dashboard.lkml
generator/dashboards/templates/model.lkml
generator/explores/operational_monitoring_explore.py
generator/lookml.py
generator/namespaces.py
generator/operational_monitoring_utils.py
generator/views/operational_monitoring_histogram_view.py
generator/views/operational_monitoring_scalar_view.py
generator/views/operational_monitoring_view.py
tests/test_namespaces.py
tests/test_operational_monitoring.py

This is the follow-up for https://github.com/mozilla/bigquery-etl/pull/2513. It also removes the unnecessary generation of model files.
The `looker-hub` branch for testing is [here](https://github.com/mozilla/looker-hub/tree/emtwo/submission_date)

Support submission_date on x-axis in operational monitoring.

---

generator/dashboards/templates/dashboard.lkml
tests/test_operational_monitoring.py

The dropdowns were broken for this reason

String filter values should be in quotes so they are not mistaken for numbers.

---

custom-namespaces.yaml
generator/explores/client_counts_explore.py
generator/explores/events_explore.py
generator/explores/explore.py
generator/explores/growth_accounting_explore.py
generator/explores/ping_explore.py
generator/views/glean_ping_view.py
generator/views/lookml_utils.py
generator/views/operational_monitoring_view.py
tests/test_events.py
tests/test_lookml.py

Fixes https://github.com/mozilla/lookml-generator/issues/310
Currently, we only have support for exposing repeated, nested fields in ping explores. There have been some requests of making these nested fields also available in other explores (client counts, event counts) etc.
Generated content on https://github.com/mozilla/looker-hub/tree/ascholtz-expand-unnested-test
Tested in Looker

Repeated nested field support for all explores

---

generator/explores/operational_monitoring_explore.py

Yesterdays run has been failing with:
```
[2021-12-07 16:39:50,967] {{pod_launcher.py:149}} INFO - Traceback (most recent call last):
[2021-12-07 16:39:50,968] {{pod_launcher.py:149}} INFO -   File "/usr/local/bin/lookml-generator", line 33, in <module>
[2021-12-07 16:39:50,968] {{pod_launcher.py:149}} INFO -     sys.exit(load_entry_point('lookml-generator', 'console_scripts', 'lookml-generator')())
[2021-12-07 16:39:50,968] {{pod_launcher.py:149}} INFO -   File "/app/lookml-generator/generator/__main__.py", line 9, in main
[2021-12-07 16:39:50,968] {{pod_launcher.py:149}} INFO -     cli("generator")
[2021-12-07 16:39:50,968] {{pod_launcher.py:149}} INFO -   File "/app/lookml-generator/generator/__init__.py", line 37, in cli
[2021-12-07 16:39:50,968] {{pod_launcher.py:149}} INFO - …
```

Check if default dimension exists when adding opmon filters

---

generator/views/view.py

Depends on https://github.com/mozilla/looker-hub/pull/33
There was some interest in having deletion_request explores in Looker. Currently, generation fails since a deletion_request had been manually added to looker-hub.

Generate deletion_request explores

---

custom-namespaces.yaml

https://bugzilla.mozilla.org/show_bug.cgi?id=1759904

[Bug 1759904] Move Fenix topsites_impression to contextual_services namespace

---

custom-namespaces.yaml

Add active_users_aggregates_attribution  to looker namespaces to enable analysis by attribution campaign, content, experiment, medium, source and variation.

Add active_users_aggregates_attribution to Looker namespaces

---

custom-namespaces.yaml

The most recent lookml-generator Airflow task is failing with:
```
google.api_core.exceptions.Forbidden: 403 GET https://bigquery.googleapis.com/bigquery/v2/projects/mozdata/datasets/search_terms_unsanitized_analysis/tables/prototype_sanitation_job_metadata?prettyPrint=false: Access Denied: Table mozdata:search_terms_unsanitized_analysis.prototype_sanitation_job_metadata: Permission bigquery.tables.get denied on table mozdata:search_terms_unsanitized_analysis.prototype_sanitation_job_metadata (or it may not exist).
```
Since the table contains cat3 data, we'll need to use the `bigquery-oauth` connection (this will enforce that Looker will ask users to authenticate when querying this table and only if they have access permissions they'll be able to do so. Otherwise by default the Looker …

Move search_term_sanitization_job_metadata_daily to spoke-private

---

generator/explores/operational_monitoring_explore.py
tests/test_operational_monitoring.py

Removing automatic aggregate table generation for OpMon tiles. 
The main reason is that aggregate tables will cache outdated information when setting x-axis to buildID. Each point of time refers to a specific build ID which gets updated during nightly ETL runs, so cached data points won't get updated in Looker.
Additionally, creating the aggregate tables is more costly than running queries for the dashboards users are actually interested in.

Remove opmon aggregate tables

---

custom-namespaces.yaml

Relates to recent ticket updating the forecasting job: https://mozilla-hub.atlassian.net/browse/DS-2075
Required for revenue forecasting work (https://mozilla-hub.atlassian.net/browse/RS-324, https://mozilla-hub.atlassian.net/browse/RS-405)

Add automated KPI forecasting tables

---

custom-namespaces.yaml

The PR https://github.com/mozilla/bigquery-etl/pull/3141  now enables to track partition sizes of the derived tables. More details are available here: https://bugzilla.mozilla.org/show_bug.cgi?id=1779053
This is a subsequent PR is to fix the looker dashboard to point to the new view i.e. `monitoring_derived.stable_and_derived_table_sizes_v1`

modify the namespace for stable and dervied table size

---

generator/views/ping_view.py

Glean ping views that union multiple sources are currently excluded from having views & explores generated.  This PR will generate views & explores for Glean ping views that union multiple sources as long as the table/view names are all the same (e.g. the VPN Glean ping union views added in mozilla/bigquery-etl#3140 for [DENG-210](https://mozilla-hub.atlassian.net/browse/DENG-210)).
[Test run results](https://github.com/mozilla/looker-hub/compare/DENG-210-glean-unioned-pings):
- `main` and `deletion_request` views & explores (re)generated for `mozilla_vpn`.
- This is the main aim of this PR, since [those got unintentionally deleted](https://github.com/mozilla/looker-hub/commit/6ff45902a248d0151dd259c49771bf27beaa19e4#diff-9a13687d374409d7375c5752b9bf34e57673d21eebe6cd43e09dec724778e730) …

Generate views & explores for Glean ping union views (DENG-210)

---

custom-namespaces.yaml

Add search monthly view to looker hub. 
Also, removes the previously added `firefox_products_search_clients_engines_sources_daily`

add search monthly view for desktop and mobile

---

generator/views/events_view.py
generator/views/view.py

This PR fixes the `cannot be calculated because of a one_to_many or many_to_many join` errors in the event explores.
These docs were helpful in figuring out the problem: https://cloud.google.com/looker/docs/best-practices/how-to-troubleshoot-when-measures-dont-come-through-a-join
To enable measures to carry through joins (such as client count and event count), we need to define a primary key in the involved views. `document_id` is the natural choice here as primary key for the event views.
I pushed the changes to a branch in looker-hub to test them and the join worked just as expected: https://github.com/mozilla/looker-hub/tree/ascholtz-events-join-test-1
cc @skahmann3

Set document_id as primary_key in event views when available

---

custom-namespaces.yaml

This table contains info that we use to determine whether to alert data scientists to sea changes in our aggregate search data metrics. Our plan is to use Looker alarms for the alerting, so I'll be making views with this table and attaching alarms to them.

Add data validation metrics table

---

custom-namespaces.yaml

Also, remove `desktop` from the name. It's now in the desktop namespace.

Fix location for crashes_daily looker view

---

custom-namespaces.yaml
generator/views/growth_accounting_view.py
tests/test_lookml.py
tests/test_namespaces.py

Seems the change resulted in expected changes:
https://github.com/mozilla/looker-hub/blob/kik-generation-test-1/firefox_accounts/views/growth_accounting.view.lkml#L103-L108

Bug(DS-2132): FxA accounts dashboard is broken client id not found

---

bin/generate

New [looker-hub](https://github.com/mozilla/looker-hub) publish branches (e.g. for testing [lookml-generator](https://github.com/mozilla/lookml-generator) code changes) were being created from the [`base` branch](https://github.com/mozilla/looker-hub/tree/base), which resulted in essentially every file showing up as changed on such branches after lookml-generator runs.
This will now work the same as new [looker-spoke-default](https://github.com/mozilla/looker-spoke-default) publish branches, which are [also being created from its `main` branch](https://github.com/mozilla/lookml-generator/blob/83048aa9cdefcf6c66bc82ecce64b67606c049d4/bin/generate#L129).

Create new looker-hub publish branches from `main` branch

---

custom-namespaces.yaml

Adds two new views under the experimentation namespace. One is for results from the desktop existing user holdback and the other is from the desktop new user holdback. Both views point directly to Jetstream created BigQuery views (not tables, but BQ views).

Make 2022 MR jetstream outputs available in Looker

---

generator/views/glean_ping_view.py
requirements.txt
tests/test_glean_ping_view.py
tests/test_lookml.py

Reference url metrics under their other name (`url2`) in generated views

---

generator/namespaces.py

current import path will be removed in python 3.10

Fix deprecation warning for relocated import

---

custom-namespaces.yaml
generator/views/client_counts_view.py

The `firefox_desktop` namespace now has multiple client count explores. However, when generating the views they are currently always named `client_counts`. So the same view gets overridden. Instead we want to be able to generate multiple client count views and use their configured names.
cc @rebecca-burwei

Support multiple client count views in a single namespace

---

custom-namespaces.yaml

We'll have to implement the client count logic manually in an explore in spoke default.
See discussion in https://mozilla.slack.com/archives/C01J4BPCYGM/p1668102223113389
cc @rebecca-burwei

Sponsored tiles as normal views instead of client count views

---

custom-namespaces.yaml

These names are needed to import this data from BigQuery into Looker.

Add search terms daily to Looker

---

custom-namespaces.yaml

Follow up to https://github.com/mozilla/lookml-generator/pull/581. More or less matched other generated namespace entries. Tested by copying the generated lookml into looker-hub and got working queries for the explore. (Just pushing this through since @Iinh is out and validation is broken)

Updated custom namespace references for glean events explore to match other glean apps

---

.gitignore
custom-namespaces.yaml

In order to monitor Relay metrics in real time, the derived tables were created in [this PR](https://github.com/mozilla/bigquery-etl/pull/3482). They need to be added to Looker for the Relay SaaSboard.

[DS-2284]Adding Relay tables to custom-namespace.yaml for Relay SaaSboard

---

generator/views/ping_view.py
generator/views/table_view.py

The same table was being repeated for a view if the Glean app had multiple release channels (due to the [special case logic which overrides the dataset for release channels](https://github.com/mozilla/lookml-generator/blob/09cdf4c404c07c4c5dc0ee8508646bce85f8e1ef/generator/namespaces.py#L202-L220)), which the `mozilla_vpn` app currently does after https://github.com/mozilla/probe-scraper/pull/552.  This resulted in unnecessary `channel` parameters being added to all the affected views.
This will hopefully resolve the errors in the VPN Looker views related to `channel` parameters/fields in [DENG-690](https://mozilla-hub.atlassian.net/browse/DENG-690) "_Various errors in looker-spoke-default_".
However, it doesn't address the fundamental complications involved:
- Some apps like …

Avoid repeating the same table multiple times for a view (DENG-690)

---

generator/lookml.py
generator/namespaces.py
generator/views/datagroups.py
generator/views/lookml_utils.py
tests/test_datagroups.py
tests/test_namespaces.py

Implementation of the [datagroup generation proposal](https://docs.google.com/document/d/1dPwa5KZnKHzYj3hULHy9unczCXugwr6rZHW1gveQ2fc/edit#heading=h.5x0d5h95i329), see also [DENG-676](https://mozilla-hub.atlassian.net/browse/DENG-676).
Split into a small refactor to use the generated-sql function, then datagroup generation with tests.

Generate datagroups

---

generator/views/datagroups.py
tests/test_datagroups.py

Some views reference the same table. For example `mozdata.org_mozilla_ios_klar.baseline_clients_daily` and `mozdata.org_mozilla_ios_klar.baseline_clients_first_seen` are both views to `moz-fx-data-shared-prod.org_mozilla_ios_klar_derived.baseline_clients_daily_v1`.
We only need a single datagroup generated in cases like this.

Only generate one datagroup per-table

---

generator/views/datagroups.py
tests/test_datagroups.py

`interval_trigger` seems to be unsupported in the `lkml` library. This is causing invalid lookml:
e.g. 
```
...
max_cache_age: "24 hours"
interval_trigger: 6 hours
```
I'll take a look upstream as well but this should fix it as well.

Fix unquoted interval_trigger subparameter

---

generator/views/datagroups.py
tests/test_datagroups.py

I misinterpreted what the `interval_trigger` parameter does here. I though it was the interval between SQL triggers, but this is actually controlled by the maintenance schedule in the Admin panel: https://cloud.google.com/looker/docs/connecting-to-your-db#pdt_and_datagroup_maintenance_schedule. 
`interval_trigger` actually triggers the datagroup, so invalidates the cache for explores and/or triggers PDT rebuilds. 
PR removes interval triggers from datagroup definitions.

Remove interval trigger from datagroup generation entirely

---

custom-namespaces.yaml

Doing this for 2 reasons: (1) currently datagroups only get generated for `table_view`'s and (2) these actually aren't ping tables. 
This will remove this measure:
```
measure: clients {
type: count_distinct
sql: ${client_id} ;;
}
```
from both hub views so we'll have to redefine it in the spoke. 
The corresponding explores are defined as ping explores:
```
explores:
desktop_search_counts:
type: ping_explore
views:
base_view: search_clients_engines_sources_daily
mobile_search_counts:
type: ping_explore
views:
base_view: mobile_search_clients_engines_sources_daily
```
But these aren't ping tables, this makes me think there's a missing (auto-generated) Explore type here? I'm not actually sure why these explores were auto-generated.

Search view type ping_view -> table_view

---

generator/explores/explore.py
generator/views/ping_view.py
tests/test_lookml.py

The parameter switched out the underlying table to be queried. However we now have UNIONed tables for every variant of an application, making the first table contain data from all channels. Instead we now filter by `normalized_channel` and enforce that filter in explores.
---
I need to once more check that this now works as expected.

Bug 1823627 - Use a channel filter instead of a parameter switching out the table

---

custom-namespaces.yaml

This is a stopgap solution to support SubPlat’s metrics reporting until the new ETLs are completed.

Add `subscription_platform` namespace to expose existing ETL tables (DS-2934)

---

custom-namespaces.yaml

Relates to https://mozilla-hub.atlassian.net/browse/RS-733. 
1. Rename `contextual_services` to `contextual_services_private` (spoke remains `looker-spoke-private`)
2. Add new namespace `contextual_services` which is defaulted to public.
Note - the `pretty_name` will remain `Contextual Services` for both namespaces
3. Add the fill rate `mozdata view` to the public namespace.

RS 733 - Create public ctx srvcs namespace

---

generator/views/table_view.py
generator/views/view.py

Example:
```yaml
foo_namespace:
views:
bar_table:
type: table_view
tables:
- table: ...
measures:
count:
type: count
client_count:
type: count_distinct
sql: client_id
```

Allow `table_view` measures to be defined in `custom-namespaces.yaml`

---

generator/spoke.py
tests/test_spoke.py

By default, spoke-default PRs (e.g. https://github.com/mozilla/looker-spoke-default/pull/563) that create models auto-generate includes to a number of directories (as well as create empty directories). It seems like pointing to the empty created directories no longer prevents LookML warnings. One way to solve this is by manually editing the PR to comment out or remove the includes that won't have content. 
This PR automatically generates the includes as comments so merging by default won't break the production spokes.

Move includes in spoke model generation to footer comment.

---

custom-namespaces.yaml

Related to [Bug 1843890](https://bugzilla.mozilla.org/show_bug.cgi?id=1843890)
The table suggest_revenue_levers was added to both ctx private and ctx. The view should belong to ctx private given the access restrictions on the underlying tables.

Fix ctx revenue levers table in custom yaml

---

custom-namespaces.yaml

with https://github.com/mozilla/bigquery-etl/pull/4173 we added more airflow monitoring tables that should be exposed in looker.
Also the monitoring folder is quiet big and the prefix `airflow_` helps to keep all the views in order and know what they are related to.
Not sure if renaming gets rid of the old views in Looker yet

feat(DENG-1360): add more airflow monitoring and rename old once

---

custom-namespaces.yaml

Adds Looker views for the BigQuery views being added in mozilla/bigquery-etl#4166 (which has been approved and I anticipate merging today).

Add SubPlat logical subscriptions views (DS-3082)

---

custom-namespaces.yaml

Fixing the name of the explore so it doesn't conflict with the names of existing explores. 
Why I think this will fix it: https://github.com/mozilla/lookml-generator/blob/main/generator/explores/events_explore.py#L40

Take 2: Add urlbar events to Looker

---

custom-namespaces.yaml

This view was redundant and has been deleted

Remove consolidated_ad_metrics_hourly from namespace

---

custom-namespaces.yaml

I'm pretty sure this should work. The lkml library [adds semicolons to SQL statements](https://github.com/joshtemple/lkml/issues/51), so we don't need to add those to the measure definitions.
note: I wrote this manually in the Github editor, so lmk if you see something off in the yaml.

Add explore for gplay data

---

custom-namespaces.yaml

Checks have been removed from the Platform Health Check dashboard

Remove references to distinct_docids

---

generator/views/glean_ping_view.py
tests/test_glean_ping_view.py

This should have been done when we changed the Glean ping views to convert datetime metrics to timestamps (mozilla/bigquery-etl#3453).
Instead, [invalid LookML ended up getting generated](https://github.com/mozilla/looker-hub/commit/2291a2f41fe4fb9d8ea640a83ce84a10bbcf6362) that went unnoticed, until today when Looker started showing `"type": time may only be used in a dimension_group` errors during LookML validation.

Generate time dimension groups for datetime metrics in Glean ping views

---

generator/views/glean_ping_view.py
tests/test_glean_ping_view.py

LookML validation is failing with `Invalid property for "dimension_group": link` errors for the 106 current such datetime metric dimension groups.

Remove invalid link properties from datetime metric dimension groups in Glean ping views

---

generator/views/client_counts_view.py

I've ran into some issues where joining the Client Counts view with other views that had a `client_id` field raised `Column name client_id is ambiguous`

COUNT(DISTINCT ${TABLE}.client_id) in client count views

---

custom-namespaces.yaml

Add desktop acquisition funnel sample table to start dashboarding. Will be replaced by permanent view once available. Metrics should stay the same but will likely have additional dimensions.

Add desktop acquisition funnel sample table to start dashboard layout

---

custom-namespaces.yaml

follows-up: https://github.com/mozilla/bigquery-etl/pull/4425

feat(): Adding fenix funnel_retention_week_4 table view to custom-namespaces

---

custom-namespaces.yaml

This generates a view for the new `stripe_subscriptions_v2` table.
Depends on mozilla/bigquery-etl#4712.

Generate view for `stripe_subscriptions_v2` (DS-3079)

---

custom-namespaces.yaml

Depends on: https://github.com/mozilla/looker-spoke-default/pull/685

feat(DENG-2215): removed data integrity namespace as it was pointing to DIM datasets which are being deprecated

---

custom-namespaces.yaml

Follow up to: https://github.com/mozilla/bigquery-etl/pull/4648

feat(): fenix and firefox_ios table views added for product feature usage tables

---

generator/views/lookml_utils.py

The newly added events stream tables have a string field `event` and an `event_timestamp` field. `event_timestamp` should be handled similar to submission_timestamp.
Currently lookml-generator is failing with `Error: duplicate dimension 'event' for table 'mozdata.org_mozilla_fenix.events_stream'`

Fix handling event stream tables

---

generator/views/lookml_utils.py

This should unblock lookml-generator that's now failing with `Error: duplicate dimension 'attribution_dltoken' for table 'mozdata.firefox_desktop.desktop_installs'`.

Fix handling firefox_desktop.desktop_installs

---

custom-namespaces.yaml

https://bugzilla.mozilla.org/show_bug.cgi?id=1875871
`monitoring.payload_bytes_decoded_all` has been removed from BigQuery

[Bug 1875871] Remove payload_bytes_decoded_all

---

custom-namespaces.yaml

**Added 7 new views in the websites folder:**
- ga4_www_site_downloads: moz-fx-data-marketing-prod.ga_derived.www_site_downloads_v2
- ga4_sessions: moz-fx-data-shared-prod.mozilla_org_derived.ga_sessions_v2
- ga4_www_site_hits: moz-fx-data-marketing-prod.ga_derived.www_site_hits_v2
- ga4_moz_org_page_metrics: moz-fx-data-marketing-prod.ga_derived.www_site_page_metrics_v2
- ga4_moz_org_metrics_summary: moz-fx-data-marketing-prod.ga_derived.www_site_metrics_summary_v2
- ga4_moz_org_landing_page_metrics: moz-fx-data-marketing-prod.ga_derived.www_site_landing_page_metrics_v2
- ga4_www_site_events_metrics: moz-fx-data-marketing-prod.ga_derived.www_site_events_metrics_v2

Adding 7 new GA4 tables to looker

---

generator/explores/glean_ping_explore.py
generator/views/glean_ping_view.py
tests/test_lookml.py

https://mozilla-hub.atlassian.net/browse/DENG-2802
Nested dimensions are currently not available in Glean ping explores. This PR adds them.
We already have them in some other explore types.
After merging, [this PR](https://github.com/mozilla/looker-spoke-default/pull/751) also needs to be merged since it manually adds `experiments` for messaging system
Generated lookml is here: https://github.com/mozilla/looker-hub/compare/main...glean-explores-with-nested-dimensions

Glean ping explores with nested dimensions

---

generator/spoke.py
tests/test_spoke.py

https://mozilla-hub.atlassian.net/browse/DENG-1908
This uncomments the explore import for new namespaces added to looker-spoke if explores exist, e.g. the generated ones for glean apps.  @akkomar Is there value in doing this for existing custom namespaces that have explores added?  I think it's reasonable to expect someone to update the spoke repo along with adding explores here.
No new test cases because the existing ones already cover both cases.

[DENG-1908] Auto-import existing explores for new namespaces

---

custom-namespaces.yaml

This is to avoid the same table view to be generated multiple times.
follow-up: https://github.com/mozilla/looker-spoke-default/pull/759

chore(): Removing duplicate configuration for firefox ios / android clients table

---

custom-namespaces.yaml

@scholtzan the Explores in the Monitor Frontend folder that currently exist are Glean data, but the funnel data I added here is not. I set `glean_app: true` since it's technically based on Glean. Is this okay?

Add Monitor Frontend to custom-namespaces.yaml

---

custom-namespaces.yaml
generator/spoke.py
namespaces-disallowlist.yaml

Looker artifacts for deprecated Glean apps are automatically removed from looker-hub via: https://github.com/mozilla/lookml-generator/blob/fdf36bb0e1ee52078176c562031467ce12d28b39/generator/namespaces.py#L257
We should also remove the corresponding folders in the spoke projects, which is what this PR does.
The folders will be removed as part of the auto-push PRs ([such as this one](https://github.com/mozilla/looker-spoke-default/pull/790)). 
This is part of the effort to remove content from Looker to speed things up

Remove deprecated glean apps

---

bin/generate
custom-namespaces.yaml
namespaces-disallowlist.yaml

It doesn't seem like these have been used or aren't used anymore, so we can remove the Looker content to speed up things a little

Remove Looker artifacts for namespaces that haven't been used in the last 360 days

---

custom-namespaces.yaml

The underlying table has been marked for deprecate via https://github.com/mozilla/bigquery-etl/pull/5046 so we should update Looker to remove the table from the Explore

Remove `urlbar_clients_daily` from Looker

---

custom-namespaces.yaml

During the GA3 -> GA4 migration, we had both GA3 and GA4 tables in custom namespaces YAML.  When we switched over to GA4, we found it easiest to just switch the existing GA3 tables to the new GA4 tables.  So now that the migration is done, want to clean up so we don't waste space/slow down Looker by having 2 copies of the same tables with different names.  Removing the ones that are unused and keeping the ones with downstream dependencies.

Speeding up Looker - remove unnecessary, duplicate views in custom namespaces yaml

---

namespaces-disallowlist.yaml

As discussed with the Nimbus data leads, we don't need this data in Looker

Remove Cirrus apps

---

custom-namespaces.yaml

Renaming the `google_search_impressions_*` views `google_search_console_*` as requested by the stakeholder.
https://github.com/mozilla/looker-spoke-default/pull/819 should be merged soon after this is merged to minimize LookML breakage.

Rename Google Search Console views (DENG-1733)

---

custom-namespaces.yaml

Updating dataset ID for registration and login funnels after moving them to `accounts_frontend_derived` for consistency.

Update dataset in custom-namespaces for login and registration funnels

---

generator/views/glean_ping_view.py
tests/test_glean_ping_view.py
tests/test_lookml.py

Running [Henry](https://github.com/looker-open-source/henry) on our Looker instance indicated that there are over 1200 unused explores all related to the generated `suggest__` explores that are provided for each labeled counter. The only suggest explores that have been used are for the `glean_error_invalid_label` dimensions.
This PR changes the generation logic to only generate suggest explores for specific labeled counters and removes all the unused suggest explores. This should increase platform performance.

Generate suggest explores only for specific labeled counters

---

generator/namespaces.py
generator/views/lookml_utils.py
generator/views/metric_definitions_view.py
requirements.in
requirements.txt

Depends on https://github.com/mozilla/metric-config-parser/pull/367 and https://github.com/mozilla/metric-config-parser/pull/366
Instead of having "Metric Definition" explores joined to "Client Count" explores to make them filterable, these changes allow to configure a data source in metric-hub to be used to provide these base fields. Metric hub now allows `joins` expressions between data sources

Update metric definition views to depend on data source joins

---

generator/views/metric_definitions_view.py

Prevent duplicate dimensions in metric definitions views

---

custom-namespaces.yaml

Because the BigQuery views are being moved (mozilla/bigquery-etl#5822).

Update Google Search Console views to use BigQuery views in `mozdata`

---

.circleci/config.yml

This slightly alters the configuration for CircleCI <> GCP OIDC configuration. This is a more generic approach that overrides environment variables in the context of the job to prevent environment variables collisions with project/context-level environment variables.
https://github.com/mozilla/bigquery-etl/pull/5855

chore(ci): Improve Airflow external DAG trigger.

---

custom-namespaces.yaml

Adds Looker assets for the [serp_categorization_unnested view](https://github.com/mozilla/private-bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/firefox_desktop/serp_categorization_unnested/view.sql) (private-bqetl).

Add view & explore for serp category data

---

generator/views/lookml_utils.py
tests/test_lookml.py

Alternative to https://github.com/mozilla/lookml-generator/pull/1007 that would fix https://github.com/mozilla/bigquery-etl/issues/5903, implements suggestion from https://github.com/mozilla/lookml-generator/pull/1007#discussion_r1678304804.
This approach seems to be minimally invasive and generalized, without hardcoding table names, allowing to unblock https://github.com/mozilla/bigquery-etl/issues/5903.

Allow same names for dimensions and time dimension groups in generated views

---

custom-namespaces.yaml

I just added these two views in bigquery-etl. This PR should surface them in Looker such that they can be included in dashboards.

Add custom namespaces to surface tables in Looker

---

custom-namespaces.yaml

I think this was missed in https://github.com/mozilla/lookml-generator/pull/1025/.  lookml is currently failing with `Not found: Dataset moz-fx-data-marketing-prod:mozilla_org`

Change www_site_downloads to shared prod

---

custom-namespaces.yaml

Depends on mozilla/bigquery-etl#6027.

Add limited historical Google Search Console views (DENG-4329)

---

.circleci/config.yml
pytest.ini
requirements.in
requirements.txt

`pytest-flake8` does only support `flake8` < version 5 (`flake8`s current version is 7+). It seems like support for `pytest-flake8` is limited, so this PR has `flake8` run as a separate CI check. 
Fixes the failing dependabot PRs: https://github.com/mozilla/lookml-generator/pull/1014

Flake8 as separate CI check

---

requirements.in
requirements.txt

The plan is to use `spectacles` to run some Looker content validation via Airflow (after lookml-generator runs). The content validation can be set on a per folder level, so it finishes relatively quickly and validates dashboards and related explores. Hopefully, this way we can detect breakages faster. 
This PR installs `spectacles` as part of the `lookml-generator` docker container which will be used in Airflow. (PR to come)

Install spectacles used for validating lookml

---

custom-namespaces.yaml

new_profiles aggregate table view added for the following mobile products:
- `fenix`
- `focus_android`
- `klar_android`
- `firefox_ios`
- `focus_ios`
- `klar_ios`

feat(): add new_profiles table views to mobile product namespaces

---

requirements.in
requirements.txt

The new `mozilla-nimbus-schema` version now supports recent pydantic versions, so `spectacles` can be upgraded to the most recent version

Update dependencies related to spectacles

---

custom-namespaces.yaml

This not needed as we want the union of all to be exposed instead in Looker.

feat: remove new_profiles from mobile product specific namespaces

---

custom-namespaces.yaml

As I learn more about Looker, I realize I needed to create some explores
in the spoke project that join across these various views. I'll be
creating an explore that joins across the three "task" tables, an
explore that joins across the two "worker" tables, and possibly an
explore that joins everything?
With these new explores, I don't think there will be any use case for
keeping table specific explores lying around.

fxci: add some measures and remove unnecessary table explores

---

custom-namespaces.yaml

feat: deprecate funnel_retention_week_4 table views for fenix and firefox_ios as superseded by mobile_retention

---

namespaces-disallowlist.yaml

I did another run of [Henry](https://github.com/looker-open-source/henry) to see which namespaces haven't been used in the last 180 days. These namespaces seem safe to remove to reduce the number of Looker artifacts and gain some potential performance improvements

Remove unused namespaces

---

generator/explores/metric_definitions_explore.py

This is to increase performance of the Metric Definition explores. Setting sampling to 1% by default.

Set default sampling filter to 1% for metric definiton explores

---

generator/explores/explore.py
generator/lookml.py
tests/test_events.py
tests/test_funnel_analysis.py
tests/test_lookml.py
tests/test_namespaces.py
tests/test_operational_monitoring.py

This adds an option to make generated explores hidden.
This will be useful for https://mozilla-hub.atlassian.net/browse/DENG-2407 where we are deprecating custom ping in favor of `events` ping. Hiding the custom ping explore will make working with Looker less confusing to users. It will also ensure that no new dashboards are built with explore in question and existing ones will not break.
In order to hide autogenerated explore we'll need to put it in `custom-namespaces` with `hidden: true`. Specifically, for DENG-2407 this would look like:
```
accounts_backend:
explores:
accounts_events:
hidden: true
type: glean_ping_explore
views:
base_view: accounts_events
```

DENG-2407 Allow hiding generated explores

---

custom-namespaces.yaml

This is to fix https://mozilla.slack.com/archives/C01E8GDG80N/p1728324080900889
Currently, there are conflicting namespaces as `shared` already exists in spoke-default. The naming convention for private namespaces is to add a `_private` suffix. This will also resolve the conflict here.

Add shared_private namespace for country customizations

---

custom-namespaces.yaml
namespaces-disallowlist.yaml

There was a [request in Slack](https://mozilla.slack.com/archives/C03V75Q1KQS/p1728424127467039) for the Relay backend data to be made available in Looker.

Add `relay_backend` namespace

---

custom-namespaces.yaml

This PR adds the new view "metadata_completeness" to Looker, referencing: mozdata.monitoring.metadata_completeness

DENG-5757 - add new view for metadata completeness to Looker

---

generator/views/glean_ping_view.py

https://bugzilla.mozilla.org/show_bug.cgi?id=1932210
Following the instructions in https://github.com/mozilla/glean/blob/main/docs/dev/core/new-metric-type/platform.md

Bug 1932210 - Add labeled_quantity glean metric type

---

custom-namespaces.yaml

Depends on https://github.com/mozilla/looker-spoke-default/pull/989
The generated experiment search views are no longer in use and can be removed.

Remove experimentation search monitoring views

---

custom-namespaces.yaml

Adds Ads Data Team to owners of Ads namespace, and @alekhyamoz to owners of Revenue Private namespace

Change owners of Ads and Revenue Private namespaces

---

custom-namespaces.yaml

This table has been migrated to accounts_frontend dataset, view and explore are not used.

Remove legacy FxA Login Funnels

---

custom-namespaces.yaml

Like https://github.com/mozilla/lookml-generator/pull/1128, table has been migrated to accounts_frontend dataset, view and explore are not used.

Remove legacy FxA Registration Funnels

---

custom-namespaces.yaml

https://mozilla-hub.atlassian.net/browse/DENG-7019
Adding `monitoring_derived.event_monitoring_aggregates_v1` and `telemetry_derived.event_aggregates_v1` to looker
cc @kwindau as the owner of `telemetry_derived.event_aggregates_v1`

[DENG-7019] Add legacy and glean event count explores

---

custom-namespaces.yaml

`funnel_analysis` and `events_daily` views are [no longer in use](https://mozilla.acryl.io/dataset/urn:li:dataset:(urn:li:dataPlatform:bigquery,moz-fx-data-shared-prod.firefox_accounts_derived.events_daily_v1,PROD)/Lineage?is_lineage_mode=false) after migration to Glean and switch to bqetl-generated funnel queries.

Remove legacy Accounts funnel views

---

generator/views/metric_definitions_view.py

Should fix the issues that were reverted inhttps://github.com/mozilla/metric-hub/pull/736
This will remove duplicate base view dimensions that should be overridden by a joined data source

Fix join generation for metric views

---

custom-namespaces.yaml

This PR creates a new Looker view called `bigquery_shared_prod_table_storage` based on `mozdata.monitoring.table_storage`

Add new Looker reference to table_storage in custom namespaces

---

custom-namespaces.yaml

- Update accounts health tables to point to firefox_accounts_derived instead of analysis tables
- Sync up the tables: remove cost, velocity, pagerduty; add pingdom

update accounts health tables

---

custom-namespaces.yaml

Reverts https://github.com/mozilla/lookml-generator/pull/1122
The search monitoring should be added back to the enrollment monitoring dashboards

Revert "Remove experimentation search monitoring views" #1122

---

custom-namespaces.yaml

Remove datasource that no longer exists. Table has been deleted from `moz-fx-data-marketing-prod` due to lack of use and lack of updates since 2023

take out firefox_mobile_installs from custom_namespaces.yaml

---

custom-namespaces.yaml

This updates the `jira_service_desk` to use OAuth. This needs to be merged alongside https://github.com/mozilla/bigquery-etl/pull/6971 which adds access restrictions to the underlying datasets

Use OAuth for `jira_service_desk`

---

generator/views/datagroups.py

Related to https://github.com/mozilla/lookml-generator/pull/1159#issuecomment-2641335278
Datagroup creation should be skipped when underlying table is not accessible

Skip datagroup creation when running into permission error

---

custom-namespaces.yaml

This PR adds 3 new weekly retention views to Looker: 
- moz-fx-data-shared-prod.telemetry.cohort_weekly_statistics
- moz-fx-data-shared-prod.telemetry.cohort_weekly_statistics_by_app
- moz-fx-data-shared-prod.telemetry.cohort_weekly_statistics_by_app_channel_version

feat(DENG-7970): Add 3 new weekly retention views to Looker

---

generator/explores/glean_ping_explore.py

Some explores do not have `always_filter`s. Looker doesn't support an empty list of filters, so this PR only sets the `always_filter` attribute when there are filters available.
This fixes the failing Airflow task.

Fix filter generation for explores that do not need filters

---

generator/views/lookml_utils.py
tests/test_lookml.py
tests/test_operational_monitoring.py

For a nicer user experience in Looker (e.g. "OS" instead of "Os").

Uppercase some common initialisms in titles

---

generator/explores/client_counts_explore.py
generator/explores/events_explore.py
generator/explores/explore.py
generator/explores/funnel_analysis_explore.py
generator/explores/glean_ping_explore.py
generator/explores/growth_accounting_explore.py
generator/explores/metric_definitions_explore.py
generator/explores/operational_monitoring_explore.py
generator/explores/ping_explore.py
generator/explores/table_explore.py
generator/views/datagroups.py
generator/views/lookml_utils.py
tests/test_datagroups.py

https://mozilla-hub.atlassian.net/browse/DENG-8141
Closes https://github.com/mozilla/lookml-generator/issues/1089
This PR updates the LookML-Generator to:
* Include datagroups for explores referencing BigQuery views querying multiple tables. This ensures efficient cache validation
*  Expand the explore generation logic to include all types of explores, beyond the currently supported table explores
The generation logic changes slightly. Instead of creating a datagroup per BigQuery table, now a datagroup per view is being generated.
Validated here: https://github.com/mozilla/looker-hub/compare/test-datagroup-generation?expand=1
Needs to be merged with: https://github.com/mozilla/looker-spoke-default/pull/1043
Some updates to datagroups were needed as they are now generated for Looker views …

[DENG-8141] Generate datagroups and persist explores with multiple references

---

custom-namespaces.yaml

This is to define a Looker view and explore for a new derived table for HNT content reporting introduced in https://github.com/mozilla/bigquery-etl/pull/7257.
We will use this for [DENG-8082](https://mozilla-hub.atlassian.net/browse/DENG-8082).

feat(DENG-8082): Add new view and explore for HNT content reporting

---

custom-namespaces.yaml

This PR adds the following views to the reference space in Looker:
- mozdata.external.calendar
- mozdata.external.holidays
- mozdata.external.chrome_extensions
- mozdata.external.gdp
- mozdata.external.imf_exchange_rates
- mozdata.external.monthly_inflation
- mozdata.external.quarterly_inflation
- mozdata.external.population_by_country

Add new external views to custom namespaces

---

generator/views/metric_definitions_view.py

Lookml-generator removes `_date`/`_time`/`_timestamp` suffixes when generating lookml dimensions, however we
need the original field name for the derived view SQL in the metric definition views. Currently, by removing the suffixes the incorrect names are used to select these fields from the source tables
See https://mozilla.slack.com/archives/C4D5ZA91B/p1746032441161499?thread_ts=1745336833.230079&cid=C4D5ZA91B

Fix metric definition date field SQL references

---

generator/views/metric_definitions_view.py

Fixes failing lookml validation: https://workflow.telemetry.mozilla.org/dags/looker/grid?search=looker&dag_run_id=manual__2025-05-01T12%3A57%3A37.811735%2B00%3A00&task_id=validate_lookml_spoke_default_spectacles&tab=logs

Fix metric definition date field names that have `__`

---

custom-namespaces.yaml

This adds a new view to Looker:
- Looker name:     `glean_active_users_aggregates`
- Source table: `moz-fx-data-shared-prod.glean_telemetry.active_users_aggregates`

feat(DENG-8396): Add new Glean AUA view to Looker

---

.github/dependabot.yml
CODEOWNERS

https://mozilla-hub.atlassian.net/browse/DENG-8480
Dependabot reviewers configuration is being removed, and instead they are recommending to rely on CODEOWNERS files to assign reviewers

[DENG-8480] Use CODEOWNERS for tagging reviewers for dependabot

---

generator/explores/explore.py
generator/namespaces.py
namespaces-disallowlist.yaml
tests/test_namespaces.py

https://mozilla-hub.atlassian.net/browse/DENG-8623
Based on proposal: https://docs.google.com/document/d/1CJq_avwso-fK7F4H3483brw8yAYFA0VQbgrfOA5ZY3s/edit?tab=t.0
Our Looker instance has a lot of generated LookML, some of which is very rarely or never being looked at. lookml-generator automatically generates a set of views and explores for every Glean application. The amount of LookML content is impacting the overall performance of our Looker instance. 
This extends the existing namespaces-disallowlist.yaml to exclude views and explores from being generated.

[DENG-8623] Mechanism to exclude generated LookML content

---

custom-namespaces.yaml

This PR adds the following views into Looker:
- firefox_com_ga4_www_site_downloads (moz-fx-data-shared-prod.firefoxdotcom.www_site_downloads)
- firefox_com_ga4_sessions (mozdata.firefoxdotcom.ga_sessions)
- firefox_com_page_metrics (moz-fx-data-shared-prod.firefoxdotcom.www_site_page_metrics)
- firefox_com_metrics_summary (moz-fx-data-shared-prod.firefoxdotcom.wwww_site_metrics_summary)
- firefox_com_www_site_events_metrics (mozdata.firefoxdotcom.www_site_events_metrics)
- firefox_com_landing_page_metrics (moz-fx-data-shared-prod.firefoxdotcom.www_site_landing_page_metrics)
- firefox_com_firefox_whatsnew_summary (mozdata.firefoxdotcom.firefox_whatsnew_summary)

feat(DENG-8699): Add new firefox.com views to Looker

---

namespaces-disallowlist.yaml

Depends on https://github.com/mozilla/looker-spoke-default/pull/1086
These are some of the models and pings that have not been used in at least 90 days or longer based on https://mozilla.cloud.looker.com/dashboards/2375
I already checked that no dashboard depends on any of these artifacts (and if so archived them).
See generated LookML: https://github.com/mozilla/looker-hub/compare/ascholtz-remove-unused-3?expand=1
Manually tested and validated in Looker

Exclude unused models and pings

---

custom-namespaces.yaml

The underlying `mozdata.analysis.desktop_search_alert_records` got removed. There are no dashboards referencing this explore, so we can just delete it.

Remove desktop_search_alert_records

---

custom-namespaces.yaml

This PR adds a new view called `cohort_churn` in the `combined_browser_metrics` namespace that points at the view: 
- `moz-fx-data-shared-prod.telemetry.cohort_daily_churn`

Add cohort_daily_churn to looker

---

custom-namespaces.yaml

There was a looker view called "fenix_distribution_deal" pointing to the table `mozdata.analysis.fenix_distribution_deal_v1`, but this table no longer exists.  This is causing errors in the Looker DAG.

Remove table that no longer exists from Looker

---

custom-namespaces.yaml
namespaces-disallowlist.yaml

The firefox_desktop_background_update and thunderbird_desktop are not in use and can be removed. There are some fenix explores and monitoring explores which are also not in use and removed as part of this pr
Depends on https://github.com/mozilla/looker-spoke-default/pull/1138

feat(DENG-9322) Remove unused models and explores for fenix and monitoring

---

Dockerfile

The `build-container` CI jobs started failing this week with the error "_Unable to locate package software-properties-common_".
The `Dockerfile` was updated to install the `software-properties-common` package back in 2021 to facilitate installing the GitHub CLI (#52), and luckily it appears that installing `software-properties-common` is actually no longer necessary.

fix: Don't try to install `software-properties-common` package

---

namespaces-disallowlist.yaml

This adds the 2 `firefox_desktop` views/explores to the disallow list:
- deletion_request
- pseudo_main

feat(DENG-9334): Delete unused Firefox desktop views & explores

---

namespaces-disallowlist.yaml

This PR removes the following unused views/explores from the `firefox_desktop` namespace: 
- pageload_domain
- pageload_base_domain
- events_stream_table
- profiles
- quick_suggestion_deletion_request
- serp_categorization
- third_party_modules
- top_sites

feat(DENG-9334): Remove some explores/views from Firefox Desktop namespace

---

namespaces-disallowlist.yaml

Remove the following unused views from the `firefox_desktop` namespace:
- nimbus_targeting_context
- onboarding_opt_out
- update

feat(DENG-9334): Remove un-used views/explores from Firefox Desktop namespace

---

namespaces-disallowlist.yaml

This PR adds the following unused views/explores to firefox_desktop namespace disallow list:
- sync
- urlbar_keyword_exposure

feat(DENG-9334): Add unused views/explores to firefox_desktop namespace disallow list

---

namespaces-disallowlist.yaml

This PR removes `user_characteristics` view & explore from Firefox Desktop namespace since it's unused.

feat(DENG-9334): Add user_characteristics to namespace disallow list

---

custom-namespaces.yaml

Implements [AD-1040](https://mozilla-hub.atlassian.net/browse/AD-1040).
Enables deprecation of older views.
Keeping the view names for compatibility and less impact on users.

Update Looker views to use ad_metrics

---

custom-namespaces.yaml

This PR updates the Looker view `ga4_sessions` to point to the view `moz-fx-data-shared-prod.mozilla_org.ga_sessions` , instead of the view `moz-fx-data-shared-prod.mozilla_org.ga_sessions_v2`

Switch ga4_sessions to reference view, not table

---

.flake8
generator/explores/metric_definitions_explore.py
generator/views/metric_definitions_view.py

Reverts mozilla/lookml-generator#1293

Revert "[DENG-8655] Period-over-period support for metric-hub metrics"

---

custom-namespaces.yaml

Updates the `reference` namespace:
* remove deprecated `macroeconomic_indices` view
* reassign ownership

DENG-9325 Remove deprecated view and reassign namespace ownership

---

custom-namespaces.yaml

This swaps out the new view with the newtab-content ping data. The schema will be functionally the same with a couple of small changes and is only used in one explore.

feat: swap newtab_items_daily_v1 with new view newtab_content_items_daily_combined_v1

---

custom-namespaces.yaml

See https://github.com/mozilla/bigquery-etl/pull/8164.
This is currently [causing LookML generation to fail](https://workflow.telemetry.mozilla.org/dags/looker/grid?dag_run_id=manual__2025-09-26T20%3A17%3A44.899677%2B00%3A00&task_id=lookml_generator_staging&tab=logs).

fix: Remove reference to the `ios_app_campaign_stats` table, which has been deleted

---

custom-namespaces.yaml

Create new Looker hub view: ga4_blog_performance, which points to BQ view: `mozdata.mozilla_org.blog_performance`

feat(DENG-9765): Add blog performance
